### GENERAL SETTINGS ###

# Site settings
title: Dongmei
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" 
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  # - title: dribbble
  #   url:
  - title: github
    url: https://github.com/dongmei
  - title: twitter
    url: https://twitter.com/zoeMeii
  # - title: instagram
  #   url: 
  - title: linkedin
    url: https://sg.linkedin.com/in/hu-dongmei-5387621b
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Bishan Street 24
    - Singapore
email: zoe.94heather@gmail.com
tel: +65 9692 1526


# ### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# # Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
# about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# # Testimonial content. Shown on Home and About page. 
# testimonial:
#     message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
#     author: Marcel Newman
#     position: WEB DESIGNER - BLACKTIE.CO