# Site settings
title: Dongmei's portfolio
email: zoe.94heather@gamil.com
description: > # this means to ignore newlines until "baseurl:"
  # A simple, whitespace, helvetica based portfolio 
  Dongmei's portfolio 
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: zoemeii
github_username:  dongmei

# Build settings
markdown: kramdown

#highlighter: pygments

# Pagination
#paginate: 15
#paginate_path: "/blog/page:num/"


collections:
  design:
    output: true
    permalink: /design/:path/

  handcraft:
    output: true
    permalink: /handcraft/:path/

  blog:
    output: true
    permalink: /blog/:path/

